tinyMCE.addI18n('pt.advanced',{
style_select:"Estilos",
font_size:"Tamanho da Fonte",
fontdefault:"Fonte",
block:"Formata\u00E7\u00E3o",
paragraph:"Par\u00E1grafo",
div:"Div",
address:"Endere\u00E7o",
pre:"Pre-formatado",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code exemplo",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"It\u00E1lico (Ctrl+I)",
underline_desc:"Underline (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"Alinhamento Esquerda",
justifycenter_desc:"Alinhamento Central",
justifyright_desc:"Alinhamento Direita",
justifyfull_desc:"Alinhamento Cheio",
bullist_desc:"Lista n\u00E3o-ordenada",
numlist_desc:"Lista Ordenada",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/editar link",
unlink_desc:"Unlink",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar c\u00F3digo",
code_desc:"Editar HTML",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Inserir linha horizontal",
removeformat_desc:"Remover formata\u00E7\u00E3o",
custom1_desc:"Sua descri\u00E7\u00E3o customizada aqui",
forecolor_desc:"Selecione a cor do texto",
backcolor_desc:"Selecione a cor de fundo",
charmap_desc:"Inserir caractere customizado",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Inserir/editar \u00E2ncora",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da Imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Blockquote",
clipboard_msg:"Copiar/Cortar/Colar n\u00E3o est\u00E1 dispon\u00EDvel no Mozilla e Firefox.\nDeseja maiores informa\u00E7\u00F5es sobre esse problema?",
path:"Caminho",
newdocument:"Voc\u00EA tem certeza que deseja limpar todo o conte\u00FAdo?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"Mais Cores"
});