tinyMCE.addI18n('pt.advanced_dlg',{
about_title:"Sobre o TinyMCE",
about_general:"Sobre",
about_help:"Ajuda",
about_license:"Licen\u00E7a",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Author",
about_version:"Version",
about_loaded:"Loaded plugins",
anchor_title:"Inserir/editar ancora",
anchor_name:"Anchor name",
code_title:"HTML Source Editor",
code_wordwrap:"Word wrap",
colorpicker_title:"Selecione uma cor",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"Color picker",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Cores da Paleta",
colorpicker_named_tab:"Nomeadas",
colorpicker_named_title:"Cores nomeadas",
colorpicker_color:"Cor:",
colorpicker_name:"Nome:",
charmap_title:"Selecione o caractere customizado",
image_title:"Inserir/editar imagem",
image_src:"URL da imagem",
image_alt:"Descri\u00E7\u00E3o",
image_list:"Lista",
image_border:"Borda",
image_dimensions:"Dimens\u00F5es",
image_vspace:"Espa\u00E7amento vertical",
image_hspace:"Espa\u00E7amento horizontal",
image_align:"Alinhamento",
image_align_baseline:"Baseline",
image_align_top:"Top",
image_align_middle:"Middle",
image_align_bottom:"Bottom",
image_align_texttop:"Text top",
image_align_textbottom:"Text bottom",
image_align_left:"Left",
image_align_right:"Right",
link_title:"Inserir/editar link",
link_url:"Link URL",
link_target:"Target",
link_target_same:"Abrir na mesma janela",
link_target_blank:"Abrir em uma nova janela",
link_titlefield:"T\u00EDtulo",
link_is_email:"O endere\u00E7o url que voc\u00EA forneceu parece ser um endere\u00E7o de e-mail, voc\u00EA deseja acrescentar o prefixo requerido mailto: ?",
link_is_external:"O endere\u00E7o url que voc\u00EA forneceu parece ser um link externo, voc\u00EA deseja adicionar o prefixo requerido http:// ?",
link_list:"Lista de links"
});